package com.practice.task_scheduler.exceptions;

import jakarta.validation.Valid;
import lombok.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    USER(1000, "USER ERROR", HttpStatus.BAD_REQUEST),
    USER_EXISTED(1001, "USER EXISTED", HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND(1002, "USER IS NOT FOUND", HttpStatus.NOT_FOUND),
    USER_PASSWORD_INCORRECT(1003, "PASSWORD IS INCORRECT", HttpStatus.UNAUTHORIZED),
    USER_PASSWORD_FOUND(1013, "PASSWORD USED", HttpStatus.BAD_REQUEST)
    ,

    TASKLIST_EXCEPTION(2000, "TASK LIST EXCEPTION", HttpStatus.BAD_REQUEST),
    TASKLIST_ALREADY_EXIST(2001, "TASK lIST ALREADY EXIST", HttpStatus.BAD_REQUEST),
    TASKLIST_NOT_FOUND(2002, "TASK LIST NOT FOUND", HttpStatus.NOT_FOUND),
    TASKLIST_ACCESS_DENIED(2003, "ACCESS DENIED", HttpStatus.FORBIDDEN),
    TASKLIST_INVALID_SHARECODE(2004, "INVALID SHARE CODE", HttpStatus.FORBIDDEN),
    TASKLIST_NOT_SHARED(2005, "TASK LIST IS NOT SHARED", HttpStatus.FORBIDDEN),
    TASKLIST_CANNOT_JOIN(2006, "CANNOT JOIN TASK LIST", HttpStatus.BAD_REQUEST)
    ,

    TASK_NOT_FOUND(3001, "TASK NOT FOUND", HttpStatus.NOT_FOUND),
    TASK_ACCESS_DENIED(3002, "ACCESS DENIED TO TASK", HttpStatus.FORBIDDEN),
    TASK_ALREADY_COMPLETED(3003, "TASK IS ALREADY COMPLETED", HttpStatus.BAD_REQUEST),
    TASK_INVALID_DUE_DATE(3004, "DUE DATE CANNOT BE IN THE PAST", HttpStatus.BAD_REQUEST),
    TASK_ASSIGNMENT_FAILED(3005, "CANNOT ASSIGN TASK TO NON-MEMBER", HttpStatus.BAD_REQUEST),
    TASK_IS_NOT_COMPLETED(3007,"TASK IS NOT COMPLETED", HttpStatus.BAD_REQUEST)
    ,
    RECURRENCE_ALREADY_EXIST(4000, "TASK RECURRENCE ALREADY EXIST", HttpStatus.BAD_REQUEST),
    RECURRENCE_CANNOT_BE_BEFORE_NOW(4001, "RECURRENCE CANNOT BE BEFORE NOW", HttpStatus.BAD_REQUEST),
    RECURRENCE_NOT_FOUND(4002, "RECURRENCE NOT FOUND", HttpStatus.BAD_REQUEST),
    RECURRENCE_INVALID_INTERVAL(4003, "INTERVAL NOT INVALID, AT LEAST 1", HttpStatus.BAD_REQUEST)
    ,
    USERTASKLIST_NOT_FOUND(5001, "USER OR TASKLIST NOT FOUND", HttpStatus.NOT_FOUND)
    ,
    USERTASK_NOT_FOUND(6001, "CANNOT FIND ANY USER AS YOU FIND", HttpStatus.NOT_FOUND),
    USERTASK_ASSIGNMENT_NOT_FOUND(6002, "CANNOT FIND ANY ASSIGNMENT", HttpStatus.NOT_FOUND)
    ,

    DATABASE_EXCEPTION(10000, "DATABASE EXCEPTION", HttpStatus.BAD_REQUEST),
    SQL_EXCEPTION(10001, "SQL EXCEPTION: INVALID SQL OPERATOR", HttpStatus.BAD_REQUEST),
    NULL_POINTER_EXCEPTION(10002, "NULL POINTER EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR)
    ,
    /*
        SUB CLASS:{
            DataIntegrityViolationException - Foreign Key Violation
            BadSqlGrammarException  - SQL syntax in @Query


     */

    FILE_EXCEPTION(11000, "FILE EXCEPTION", HttpStatus.BAD_REQUEST),
    FILE_PROCESS(11001, "ERROR IN PROCESS FILE", HttpStatus.PROCESSING),
    FILE_NOT_EXIST(11002, "FILE UPLOAD IS NOT EXIST", HttpStatus.NOT_FOUND),
    FILE_TOO_LARGE(11003, "FILE MUST BE <10Mb", HttpStatus.PROCESSING),
    FILE_TYPE_NOT_SUPPORTED(11004, "FILE IS NOT SUPPORTED", HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    FILE_UPLOAD_FAILED(11005, "UPLOAD FAILED", HttpStatus.PROCESSING)
    ,

    INTERNAL_SERVER_ERROR(12000, "INTERNAL SERVER ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    VALIDATE_ERROR(12001, "METHOD ARGUMENT NOT VALIDATE", HttpStatus.BAD_REQUEST),
    HTTP_MESSASGE_NOT_READABLE(12001, "CANNOT READ HTTP MESSAGE", HttpStatus.BAD_REQUEST)
    ;

    private final int code;
    private final String message;
    private final HttpStatusCode httpStatusCode;

}
