server:
  port: 8088
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/task_scheduler?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh}
    driver-class-name: com.mysql.cj.jdbc.Driver  #driver class name cua mysql, tryen thong tu lau roi
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
    hikari:
      auto-commit: false
  jpa:  #JPA la mot API cua Java de ket noi voi cac co so du lieu quan he
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  task:
    scheduling:
      enabled: true
api:
  prefix: api/v1

jwt:
  expiration: 2592000 #30days * 24h * 60m * 60s
  secretKey: WVok1DnZJRWsPXovJVTzB6NiNWAHwRZZoH7T7GqP8Ko=